name: build-app
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.20.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build